#pragma config(Sensor, S2,     redBack,        sensorI2CCustom)
#pragma config(Sensor, S3,     redFront,       sensorI2CCustom)
#pragma config(Sensor, S4,     compass,        sensorI2CHiTechnicCompass)
#pragma config(Motor,  motorA,          frontRight,    tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          frontLeft,     tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorC,          back,          tmotorNXT, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{

	while(true)
	{
			motor[motorC] = 100;
			motor[motorA] = 100;
			motor[motorB] = 100;
	}
}
