
#pragma config(Sensor, S2,     redBack,        sensorI2CCustom)
#pragma config(Sensor, S3,     redFront,       sensorI2CCustom)
#pragma config(Sensor, S4,     compass,        sensorI2CCustom9V)
#pragma config(Motor,  motorA,          frontRight,    tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          frontLeft,     tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorC,          back,          tmotorNXT, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*

#include "Tris10-Findball.h"
#include "compass.h"
#include "AdvancedSensors.c"

int compRelative;

task main() {
	bool limitSpeed = false;
	int speedDivision = 2;
	HTMCsetTarget(S4);
	while(true) {
		int motorSpeeds[] = {0,0,0};

		compRelative = HTMCreadRelativeHeading(S4);
		nxtDisplayString(4,"Rel:  %5d", compRelative);
		if (compRelative < -7) {
			motorSpeeds[0] = 50;
			motorSpeeds[1] = 50;
			motorSpeeds[2] = 50;
			} else if (compRelative > 7) {
			motorSpeeds[0] = -50;
			motorSpeeds[1] = -50;
			motorSpeeds[2] = -50;
			}
			else if (compRelative > -7 && compRelative < 7) {
			if (T10FBreadStrength(redFront) > T10FBreadStrength(redBack)) {
				//Front Sensor Code
				int frontValue = T10FBreadDir(redFront);

				if (frontValue == 0) {
					//No Signal
					nxtDisplayString(6, "No Signal");
					} else if (frontValue == -1) {
					//Error
					nxtDisplayString(6, "Error");
					} else if (frontValue == 3) {
					motorSpeeds[0] = -80;
					motorSpeeds[1] = 80;
					motorSpeeds[2] = 0;
					} else if (frontValue == 2) {
					motorSpeeds[0] = -80;
					motorSpeeds[1] = 40;
					motorSpeeds[2] = 28;
					} else if (frontValue == 4) {
					motorSpeeds[0] = -40;
					motorSpeeds[1] = 80;
					motorSpeeds[2] = -28;
					} else if (frontValue == 1) {
					motorSpeeds[0] = -28;
					motorSpeeds[1] = -28;
					motorSpeeds[2] = 60;
					} else if (frontValue == 5) {
					motorSpeeds[0] = 28;
					motorSpeeds[1] = 28;
					motorSpeeds[2] = -60;
				}

				nxtDisplayString(1,"Dir: %d", T10FBreadDir(redFront));
				nxtDisplayString(2,"Str: %d", T10FBreadStrength(redFront));

				} else if (T10FBreadStrength(redBack) > T10FBreadStrength(redFront)) {
				//Back Sensor Code
				int backValue = T10FBreadDir(redBack);

				if (backValue == 0) {
					nxtDisplayString(6, "No Value");
					} else if (backValue == -1) {
					//Error occoured
					nxtDisplayString(6, "Error Occurred");
					} else if (backValue == 3) {
					motorSpeeds[0] = 80;
					motorSpeeds[1] = -80;
					motorSpeeds[2] = 0;
					} else if (backValue == 2) {
					motorSpeeds[0] = 80;
					motorSpeeds[1] = -80;
					motorSpeeds[2] = 0;
					} else if (backValue == 4) {
					motorSpeeds[0] = 80;
					motorSpeeds[1] = -80;
					motorSpeeds[2] = 0;
					} else if (backValue == 1) {
					motorSpeeds[0] = 80;
					motorSpeeds[1] = -80;
					motorSpeeds[2] = 0;
					} else if (backValue == 5) {
					motorSpeeds[0] = 80;
					motorSpeeds[1] = -80;
					motorSpeeds[2] = 0;
				}

				nxtDisplayString(1,"Dir: %d", T10FBreadDir(redBack));
				nxtDisplayString(2,"Str: %d", T10FBreadStrength(redBack));

			}
		}

		int motorAVal = motorSpeeds[0];
		int motorBVal = motorSpeeds[1];
		int motorCVal = motorSpeeds[2];

		if (limitSpeed) {
			motor[motorA] = motorAVal / speedDivision;
			motor[motorB] = motorBVal / speedDivision;
			motor[motorC] = motorCVal / speedDivision;
			} else {
			motor[motorA] = motorAVal;
			motor[motorB] = motorBVal;
			motor[motorC] = motorCVal;
		}
	}
}
